Book detail 2
wolox-training/ds-angularjs pull request #1
Opened 2021-03-17 19:05 UTC by dsandoval11

## Summary
- Completed the project setup
- Added equalizer file
- Book cover image is added

## Screenshot
![image](https://user-images.githubusercontent.com/32490975/111523066-dc560a80-8728-11eb-88e7-73a9559c17ae.png)

## Trello Card
https://trello.com/c/bHFGoRJ9/27-detalle-de-libro-ii-imagen

2021-03-18 15:34 UTC, dsandoval11 commented
Roboto font is added in [PR#4](https://github.com/wolox-training/ds-angularjs/pull/4)

2021-03-19 16:23 UTC, mcallegari10 requested changes

2021-03-19 16:23 UTC, mcallegari10 commented on index.html
> +        />
```suggestion
        <img class="book-cover" src="./images/book-cover.png" alt="book-cover" />
```

No need to write it in multiple lines 😄

2021-03-19 16:23 UTC, mcallegari10 commented on index.html
> +      <div>
I think this div is not necessary

2021-03-19 16:23 UTC, mcallegari10 commented on scss/detail.scss
> +    color: #828282;
Use SASS variables for colors

2021-03-19 16:23 UTC, mcallegari10 commented on scss/detail.scss
> +    color: #828282;
Use SASS variable

2021-03-19 19:41 UTC, dsandoval11 commented on index.html
> +        />
Fixed in #3

2021-03-19 19:41 UTC, dsandoval11 commented on index.html
> +      <div>
Fixed in #3

2021-03-19 19:42 UTC, dsandoval11 commented on scss/detail.scss
> +    color: #828282;
Fixed in #2

2021-03-19 19:42 UTC, dsandoval11 commented on scss/detail.scss
> +    color: #828282;
Fixed in #2

2021-03-23 13:51 UTC, mcallegari10 approved these changes

2021-03-24 16:51 UTC, merged